services:
  postgres:
    container_name: threads-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=threads
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres-data:
